gladius:
  build: .
  command: sh -c "REDIS_IP=$(awk '$2~\"redis\"{print $1;exit}' /etc/hosts) MESOS_MASTER_IP=$(awk '$2~\"master\"{print $1;exit}' /etc/hosts) SCHEDULER_IP=$(awk 'NR==1{print $1}' /etc/hosts) GLADIUS_IP=$(awk 'NR==1{print $1}' /etc/hosts) gladius"
  environment:
    CPUS_PER_TASK: 1
    DOCKER_SOCKET: unix:///var/run/docker.sock
    EXECUTOR_ID: default
    EXECUTOR_COMMAND: /executor/gladius-executor
    FRAMEWORK_NAME: "Gladius"
    GLADIUS_PORT: 8080
    MEMORY_PER_TASK: 500
    MESOS_MASTER_PORT: 5050
    REDIS_MAX_IDLE: 3
    REDIS_IDLE_TIMEOUT: 240
    REDIS_PORT: 6379
    REDIS_PROTOCOL: tcp
    SCHEDULER_PORT: 8081
  links:
    - "redis:redis"
    - "master:master"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
  ports:
    - "8080"
    - "8081"
master:
  image: redjack/mesos-master
  environment:
    MESOS_ZK: zk://zk:2181/mesos
    MESOS_LOG_DIR: /var/log
    MESOS_WORK_DIR: /tmp
    MESOS_QUORUM: 1
  links:
    - zk
  ports:
    - "5050"
slave:
  image: redjack/mesos-slave
  environment:
    MESOS_MASTER: zk://zk:2181/mesos
    MESOS_LOG_DIR: /var/log
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: 5mins
    MESOS_ISOLATOR: cgroups/cpu,cgroups/mem
    MESOS_DOCKER_REMOVE_DELAY: 2hrs
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
    - /sys:/sys
    - /proc:/proc
    - /tmp:/executors
  links:
    - zk
  ports:
    - "5051"
redis:
  image: redis
  ports:
    - "6379"
zk:
  image: jplock/zookeeper
  ports:
    - "2181"
    - "2888"
    - "3888"
