gladius:
  net: host
  build: .
  extends:
    file: common.yml
    service: gladius
  environment:
    - REDIS_PORT_6379_TCP_ADDR=192.168.27.12
    - MASTER_PORT_5050_TCP_ADDR=192.168.27.3
    - MASTER_PORT=80
    - SCHEDULER_IP=192.168.27.12
    - SCHEDULER_PORT=8081
    - GLADIUS_PORT=80
    - CPUS_PER_TASK=.5
    - MEMORY_PER_TASK=1024
redis:
  net: host
  extends:
    file: common.yml
    service: redis
